// <auto-generated />
namespace CodigoProgramado_Grupo4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AtributoRestante2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtributoRestante2));
        
        string IMigrationMetadata.Id
        {
            get { return "202411290052054_AtributoRestante2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
