// <auto-generated />
namespace CodigoProgramado_Grupo4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RemoverImagenProducto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoverImagenProducto));
        
        string IMigrationMetadata.Id
        {
            get { return "202412011928491_RemoverImagenProducto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
